---
- name: Copy file python
  copy:
    src: samodelkin.py
    dest: /usr/local/sbin/samodelkin.py
    owner: root
    group: root
    mode: 0644

- name: Create folder if not exist
  file:
    path: "{{ conf_folder }}"
    state: directory
    recurse: yes

- name: Copy config file
  copy:
    src: samodelkin.yaml
    dest: "{{ conf_folder }}/samodelkin.yaml"
    owner: root
    group: root
    mode: 0644

- name: Copy service file
  copy:
    src: samodelkin.service
    dest: /etc/systemd/system/samodelkin.service
    owner: root
    group: root
    mode: 0644

- name: Enable & start service
  systemd:
    name: samodelkin
    daemon_reload: yes
    state: started
    enabled: True
